//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bytepad_3._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaper
    {
        public int Id { get; set; }
        public int AdminId { get; set; }
        public int SessionId { get; set; }
        public int SubjectId { get; set; }
        public int ExamTypeId { get; set; }
        public string SemesterType { get; set; }
        public string PaperType { get; set; }
        public string FileUrl { get; set; }
    
        public virtual tblAdmin tblAdmin { get; set; }
        public virtual tblExamType tblExamType { get; set; }
        public virtual tblSession tblSession { get; set; }
        public virtual tblSubject tblSubject { get; set; }
    }
}
